### PR TITLE
fix date issue

### LINKED ISSUE #280: Date is not correct
For query `who is in the sydney office right now`, it shows 14 November but the current date is 15 November.

image
**Figure: Date is not correct**

### PR DESCRIPTION
**Pull request by AttackOnMorty**
Resolves #280

### CODE REVIEW

File: src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs [hunk 1]
```diff
@@ -7,9 +7,9 @@ public static class ComponentHelper
     {
         public static DateTime ToUserLocalTime(this DateTime dateTime, DialogContext dc)
         {
-            var serverLocalTime = DateTime.SpecifyKind(dateTime, DateTimeKind.Utc);
+            var utcTime = dateTime.ToUniversalTime();
             var utcOffset = dc.Context.Activity.LocalTimestamp.GetValueOrDefault().Offset;
-            return serverLocalTime.Subtract(utcOffset);
+            return utcTime.Add(utcOffset);
```
Comment (jimmidier) [inline src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs]: There are actually two cases about date time (Sorry I didn't pay attention before)
1. ToUserLocalTime - e.g. Displaying a UTC time on user end
2. From UserLocalTime - e.g. Receiving a date string from user end and parse to UTC time for filtering

Comment (jimmidier) [reply src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs]: See my latest commit

Comment (AttackOnMorty) [reply src/SSW.SophieBot/components/SSWSophieBot.Components/ComponentHelper.cs]: Test pass in dev

image
**Figure: Date in Teams matches the current date**

**Review by jimmidier — APPROVED** [review]
